server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy-query-test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

easy-query:
  #支持的数据库
  database: mysql
  nameConversion: upper_underlined
  save-comment: true